version: '3'

vars:
  SAM_ROOT_PATH:
    sh: echo "$(pwd)/sam"

tasks:
  deploy-aws:
    desc: Deploy AWS FrontEnd Infra
    cmds:
      - echo "🚀 Deploying AWS FrontEnd Infra"
      - echo {{.SAM_ROOT_PATH}}
      - sam build --config-file {{.SAM_ROOT_PATH}}/samconfig.yaml --template-file {{.SAM_ROOT_PATH}}/template.yaml --config-env frontend
      - sam deploy --config-file {{.SAM_ROOT_PATH}}/samconfig.yaml --config-env frontend

  deploy-frontend:
    desc: Deploy Frontend
    cmds:
      - echo "🚀 Deploying Frontend"
      - rm -rf node_modules
      - rm -rf dist
      - npm install

    #vars:
    #  DEPLOY_S3_ENDPOINT: 's3://pomerium-space-platform.develop.frontend'