version: '3'

vars:
  ROOT_PATH:
    sh: echo "$(pwd)"

tasks:
  deploy-aws:
    desc: Deploy AWS FrontEnd Infra
    cmds:
      - echo "🚀 Deploying AWS FrontEnd Infra"
      - sam build --config-file {{.ROOT_PATH}}/sam/samconfig.yaml --template-file {{.ROOT_PATH}}/sam/template.yaml --config-env frontend
      - sam deploy --config-file {{.ROOT_PATH}}/sam/samconfig.yaml --config-env frontend

  deploy-application:
    desc: Deploy Application
    cmds:
      - echo "🚀 Deploying Application"
      #- rm -rf node_modules
      #- rm -rf dist
      #- npm install

      - npm run build
      
      - cmd: |
          aws s3 cp {{.ROOT_PATH}}/dist s3://ordersystem-nuvilab.frontend/ --recursive \
          --region ap-northeast-2

      - echo "🚀 Application deployed to S3"