version: '3.8'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"


  app:
    image: 969026361001.dkr.ecr.ap-northeast-2.amazonaws.com/ordersystem-backend:latest
    container_name: ordersystem-app
    depends_on:
      - mysql
    environment:
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
    ports:
      - "80:80"
volumes:
  mysql-data:
