version: 0.1

default:
  global:
    parameters:
      stack_name: ordersystem-backend-stack
  build:
    parameters:
      cached: true
      parallel: true
  validate:
    parameters:
      lint: true
  package:
    parameters:
      resolve_s3: true
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
  local_start_lambda:
    parameters:
      warm_containers: EAGER

vpc:
  deploy:
    parameters:
      capabilities: CAPABILITY_NAMED_IAM
      confirm_changeset: true
      resolve_s3: true
      profile: default
      region: ap-northeast-2
      stack_name: ordersystem-vpc-stack
      s3_prefix: ordersystem-vpc-stack
      tags:
        - group=ordersystem

ecr:
  deploy:
    parameters:
      capabilities: CAPABILITY_NAMED_IAM
      confirm_changeset: true
      resolve_s3: true
      profile: default
      region: ap-northeast-2
      stack_name: ordersystem-ecr-stack
      s3_prefix: ordersystem-ecr-stack
      tags:
        - group=ordersystem

application:
  deploy:
    parameters:
      capabilities: CAPABILITY_NAMED_IAM
      confirm_changeset: true
      resolve_s3: true
      profile: default
      region: ap-northeast-2
      stack_name: ordersystem-application-stack
      s3_prefix: ordersystem-application-stack
      tags:
        - group=ordersystem

      parameter_overrides:
        - VPCStackName=ordersystem-vpc-stack
