AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Order System Nuvilab FrontEnd Stack

Resources:

  ### S3 버킷 생성
  FrontEndS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ordersystem-nuvilab.frontend

Outputs:
  FrontEndS3Bucket:
    Description: "S3 Bucket Name"
    Value: !Ref FrontEndS3Bucket