server:
  environment: dev
  port: 80

spring:
  application:
    name: ordersystem-june

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: userpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

oauth-provider:
  google:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}